### ISSUE TITLE
Anti-Fake [Question]

### ISSUE THREAD

**Issue by EndervorHero** [KillovSky/iris#266]
Good Afternoon,
I was wondering if there is any way to expand the range of the DDI, that is, I would like to allow the numbers of Latin American countries, leaving out the virtual numbers [+1, +62, +44, +994, etc]

I don't know if this works, since the welcome function doesn't work for me, it doesn't mark an error even if it is activated

anyways, will this work?
 Thanks

![Captura](https://user-images.githubusercontent.com/78125920/133937420-e0b1fdfd-ed7b-409f-90c6-58bf761749ea.PNG)

**Comment by KillovSky** [comment]
> Good Afternoon,
> I was wondering if there is any way to expand the range of the DDI, that is, I would like to allow the numbers of Latin American countries, leaving out the virtual numbers [+1, +62, +44, +994, etc]
> 
> I don't know if this works, since the welcome function doesn't work for me, it doesn't mark an error even if it is activated
> 
> anyways, will this work?
>  Thanks
> 
> ![Captura](https://user-images.githubusercontent.com/78125920/133937420-e0b1fdfd-ed7b-409f-90c6-58bf761749ea.PNG)
> 
> 
> 
> 

Hello! Not works at this version of Íris, but the next update will use this resource, I trying to make a system that every group can set his only DDI, but for now, i cannot submit a code here because is needed to remake the anti-fake function and I have changed the base-code without completing him for now.
