### ISSUE TITLE
npm install erro

### ISSUE THREAD

**Issue by golddermax** [KillovSky/iris#405]
acontece esse erro quando eu digito npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated brainly-scraper-v2@1.1.2: The latest version is available, immediately update to get the update.
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\joao\\desktop\\iris\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, unlink 'C:\Users\joao\desktop\iris\node_modules\core-types-json-schema\package.json'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'unlink',
npm WARN cleanup       path: 'C:\\Users\\joao\\desktop\\iris\\node_modules\\core-types-json-schema\\package.json'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\joao\\desktop\\iris\\node_modules\\ignore-check',
npm WARN cleanup     [Error: EPERM: operation not permitted, unlink 'C:\Users\joao\desktop\iris\node_modules\ignore-check\node_modules\meow\readme.md'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'unlink',
npm WARN cleanup       path: 'C:\\Users\\joao\\desktop\\iris\\node_modules\\ignore-check\\node_modules\\meow\\readme.md'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joao\AppData\Local\npm-cache\_logs\2021-11-27T19_13_46_629Z-debug.log

**Comment by KillovSky** [comment]
`This is a problem related to network connectivity.` -> `Esse problema é relacionado a conectividade da internet`.

**Sempre leia o terminal.**

Ou seja, o problema aparentemente está na sua internet.

**Comment by golddermax** [comment]
> 

nao to usando nao

**Comment by Willkyz** [comment]
poderia me explicar porque esse erro esta acontecendo?

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated brainly-scraper-v2@1.1.2: The latest version is available, immediately update to get the update.
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path C:\Users\LNV\Downloads\iris-main\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find version of `python`
npm ERR!     at binaryVersion (file:///C:/Users/LNV/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users/LNV/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LNV\AppData\Local\npm-cache\_logs\2021-11-28T02_28_06_744Z-debug.log
PS C:\Users\LNV\Downloads\iris-main>

**Comment by KillovSky** [comment]
> nao to usando nao

Estranho. isso ocorre com proxy's, mas tente seguir isto aqui:

1. Remova os arquivos e faça o `git clone` novamente.

2. Rode `npm cache clean --force`, depois rode `npm config set registry="http://registry.npmjs.org/"`.

3. Instale o `NodeJS` novamente, certifique-se de usar a versão **LTS**, se ainda assim falhar, instale a versão **14** do `NodeJS`, como por exemplo, a `14.16`.

**Comment by golddermax** [comment]
> > nao to usando nao

consegui arrumar aq esse proble mas agr ta eterno nisso aq oq eu faço?

- QR code scanned. Loading session...
- QR code scanned. Loading session...
- Reinjecting api
- WAPI Reinjected
- Checking if session is valid
- Downloading patches from https://cdn.openwa.dev/patches.json
- Client is ready
- Generating patch hash
- Downloaded patches in 23.2s
- Installing patches
- Patches Installed: 8b26b
- Client loaded for normal account with 674 contacts, 162 chats & 908 messages in 112.332s
- Finalizing web session...
- Finalizing client...

**Comment by KillovSky** [comment]
> > > nao to usando nao
> 
> consegui arrumar aq esse proble mas agr ta eterno nisso aq oq eu faço?
> 
> - QR code scanned. Loading session...
> - QR code scanned. Loading session...
> - Reinjecting api
> - WAPI Reinjected
> - Checking if session is valid
> - Downloading patches from https://cdn.openwa.dev/patches.json
> - Client is ready
> - Generating patch hash
> - Downloaded patches in 23.2s
> - Installing patches
> - Patches Installed: 8b26b
> - Client loaded for normal account with 674 contacts, 162 chats & 908 messages in 112.332s
> - Finalizing web session...
> - Finalizing client...

Apague a `iris.data.json` e inicie.
