### ISSUE TITLE
Sacaron la nueva versión de iris 3.2.4? 

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#445]
Es que ando en la versión 3.1.1

**Comment by KillovSky** [comment]
Acabou de sair, peço que tenha paciência sobre as atualizações pois estou trabalhando sozinho e as vezes recebo ajuda do Pedro, por isso, as atualizações demoram, afinal, preciso refazer o comando do zero e testa-lo, e isso demora algumas horas.

Se fue ahora, les pido que tengan paciencia con las actualizaciones porque estoy trabajando solo y, a veces, recibo ayuda de Pedro, por lo que las actualizaciones tardan un tiempo, después de todo, necesito rehacer el comando desde cero y probarlo, y eso lleva unas horas.

It just left, I ask you to be patient about the updates because I'm working alone and sometimes I get help from Pedro, so the updates take a while, after all, I need to redo the command from scratch and test it, and that takes a few hours.

Desejo um bom uso da `Íris 3.2.4`!

**Comment by marru453** [comment]
@KillovSky entoces dejare la misma version iris 3.1.1 y espero la actualización de iris 3.2.4
