### ISSUE TITLE
"BUG" -> Idiomas ainda não finalizados

### ISSUE THREAD

**Issue by zaskker** [KillovSky/Iris#583]
I have this error how can I solve it?

<rejected> ReferenceError: hideMyDono is not defined
      at Object.exports.fail (C:\Users\Franco\Desktop\iris-main\iris\lib\lang\es.js:305:18)
      at kconfig (C:\Users\Franco\Desktop\iris-main\iris\lib\functions\config.js:6320:31)

**Comment by zaskker** [comment]
solved the problem was that I had to declare var hideMyDono=config.Hide_Owner_Number in Spanish and English lang

**Comment by KillovSky** [comment]
Ah, os idiomas ainda não estão 100%, alguns diálogos não funcionam ou estão instáveis, vou precisar de muito tempo para corrigir isso, pois a lista de diálogos é gigantesca.

Ah, the languages are still not 100%, some dialogs don't work or are unstable, I'll need a lot of time to fix this, because the list of dialogs is gigantic.

Ah, los idiomas aún no están al 100%, algunos diálogos no funcionan o son inestables, necesitaré mucho tiempo para arreglar esto, porque la lista de diálogos es gigantesca.

**Comment by KillovSky** [comment]
https://github.com/KillovSky/Iris/discussions/603
