### ISSUE TITLE
Download Errors and others

### ISSUE THREAD

**Issue by EndervorHero** [KillovSky/iris#75]
Good afternoon, first of all congratulations on your great bot, I also hope you are well.

- I have errors in download commands.  (downaudio, downvideo, play, video, etc)
![error1](https://user-images.githubusercontent.com/78125920/126913390-a3d25d85-b035-49a2-a18b-8cb322091f10.PNG)
![error2](https://user-images.githubusercontent.com/78125920/126913400-c5f07e53-7487-42d9-b569-efc5089fa33e.PNG)

- Others like spank, distract, heat, bed, etc. doesn't.
- Profile command doesn't work too
- I have also noticed that it no longer welcomes members.

I don't know why this happens, if I made sure to keep everything update and install FFMPEG, etc. I attach some images of the errors.

 I hope it have a solution, thank you very much.

**Comment by KillovSky** [comment]
Hello! Appears a temporary bug from patches on wa automate, but the error 404 says me something else.
This is happen because some commands send a error on the profile picture of a user, i'm trying to finish a update that will correct this errors.
The error 404 is strange, she say "server not found", maybe the server has down temporary or not, i will verify.
For now, the solution of commands that use pic from user is insert a var on the `if` line, this line have `object` too, at front of her you need to insert `The_Name_Used_on_Var == 'ERROR: 401'`, that will make the command works, but is a temporary solution.

Thanks for the advise!

**Comment by KillovSky** [comment]
I will be closing this issue, but the solution is what i said, or, you can wait the next update to get a new upgrade of corrections.

Any anothet error create a new issue, and thanks again for the bug information!
(If you have the same error, you can create another issue, but is recommended to use *that* issue).
